services:
  mongodb:
    image: 'mongo:8.0'
    environment:
      - 'MONGO_INITDB_DATABASE=hotels'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=hotels'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
